name: 🐛 Bug report
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue.

        This issue tracker is for bugs and issues.
        If you require more general support please file an issue.

        Please fill in as much of the following form as you're able.
  - type: input
    attributes:
      label: Version
  - type: textarea
    attributes:
      label: What steps will reproduce the bug?
      description: Enter details about your bug.
  - type: textarea
    attributes:
      label: How often does it reproduce? Is there a required condition?
  - type: textarea
    attributes:
      label: What is the expected behavior?
      description: If possible please provide textual output instead of screenshots.
  - type: textarea
    attributes:
      label: What do you see instead?
      description: If possible please provide textual output instead of screenshots.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Tell us anything else you think we should know.
